### ISSUE TITLE
Process Discovery

### ISSUE THREAD

**Issue by RCoanda** [xcavation/pyromorphite#13]
## Motivation

As a user I want to be able to mine a process model that describes the workflow of the process.

## Tasks

- [x] DF Graph object to make computations on for the cuts
- [x] Inductive Miner mine method
- [x] Process Tree model

- [x] Documentation for Inductive Miner
- [x] Documentation for Process Tree
- [x] Documentation for DF Graph
- [x] Tests for DF Graph

 

## References

1. Sander J.J. Leemans, Dirk Fahland, and Wil M.P. van der Aalst (2013). Discovering Block-Structured Process Models From Event Logs Containing Infrequent Behaviour. arXiv.org. Retrieved 14 February 2020, from [https://www.win.tue.nl/~dfahland/publications/LeemansFA_2013_bpi.pdf](https://www.win.tue.nl/~dfahland/publications/LeemansFA_2013_bpi.pdf)
